## .groupby()

In [ ]:
import pandas as pd 

BASE = "../datasets/Pokemon.csv"

df = pd.read_csv(BASE)

A instrução groupby tem propósito similar ao "GROUP BY" do SQL, ela agrupa um conjunto de dados em um único registro e assim como no SQL podemos usar as funções de agregação nestes registros agrupados, no caso abaixo estamos calculando a média do poder de ataque por tipo de Pokemon.

In [11]:
df.groupby("type1")["attack"].mean()

type1
Blastoise     83.000000
Bug           70.325301
Dark          83.520833
Dragon       107.024390
Electric      74.952381
Fairy         67.739130
Fighting     104.733333
Fire          86.507463
Flying        76.444444
Ghost         73.767442
Graass        50.000000
Grass         76.170213
Ground        93.952381
Ice           78.000000
Normal        75.128205
Poison        76.095238
Psychic       76.437500
Rock          92.033333
Steel         96.282051
Water         75.750000
Name: attack, dtype: float64

Podemos obter mais de uma coluna no retorno do nosso groupby, no caso abaixo estamos pegando a média do poder de ataque e defesa.

In [20]:
df.groupby("type1")[["attack", "defense"]].mean()

               attack     defense
type1
Blastoise   83.000000  100.000000
Bug         70.325301   71.518072
Dark        83.520833   67.166667
Dragon     107.024390   83.926829
Electric    74.952381   66.142857
Fairy       67.739130   70.739130
Fighting   104.733333   74.977778
Fire        86.507463   68.283582
Flying      76.444444   68.888889
Ghost       73.767442   79.488372
Graass      50.000000   90.000000
Grass       76.170213   72.117021
Ground      93.952381   86.404762
Ice         78.000000   72.078947
Normal      75.128205   60.811966
Poison      76.095238   76.857143
Psychic     76.437500   72.500000
Rock        92.033333   99.300000
Steel       96.282051  116.743590
Water       75.750000   73.477941

### Ordernando com o sort_values

No caso abaixo estamos ordernando pela coluna "attack"

df.groupby("type1")["attack"].mean().sort_values()

Podemos utilizar a argumento "ascending" para determinar que queremos uma ordenação inversa

In [28]:
df.groupby("type1")["attack"].mean().sort_values(ascending=False)

type1
Dragon       107.024390
Fighting     104.733333
Steel         96.282051
Ground        93.952381
Rock          92.033333
Fire          86.507463
Dark          83.520833
Blastoise     83.000000
Ice           78.000000
Flying        76.444444
Psychic       76.437500
Grass         76.170213
Poison        76.095238
Water         75.750000
Normal        75.128205
Electric      74.952381
Ghost         73.767442
Bug           70.325301
Fairy         67.739130
Graass        50.000000
Name: attack, dtype: float64

No cenário onde temos multiplas colunas podemos utilizar o "by" como o sort_values para determinar por qual coluna 
desejamos ordernar os registros.

In [30]:
df.groupby("type1")[["attack", "defense"]].mean().sort_values(by="attack")

               attack     defense
type1
Graass      50.000000   90.000000
Fairy       67.739130   70.739130
Bug         70.325301   71.518072
Ghost       73.767442   79.488372
Electric    74.952381   66.142857
Normal      75.128205   60.811966
Water       75.750000   73.477941
Poison      76.095238   76.857143
Grass       76.170213   72.117021
Psychic     76.437500   72.500000
Flying      76.444444   68.888889
Ice         78.000000   72.078947
Blastoise   83.000000  100.000000
Dark        83.520833   67.166667
Fire        86.507463   68.283582
Rock        92.033333   99.300000
Ground      93.952381   86.404762
Steel       96.282051  116.743590
Fighting   104.733333   74.977778
Dragon     107.024390   83.926829

### Agrupamento com duas colunas (criando subgrupos).

É possível criarmos subgrupos no retorno do nossa consulta com o groupby. Uma vez que passemos duas colunas para a função ela vai agrupar todos os registros pela primeira coluna e dentro do resultado vai agrupar novamente cada conjunto de registros pela segunda. No cenário abaixo temos todos os pokemons agrupados pelos seus tipos e dentre cada grupo de tipos temos a informação sobre pokemons legendários ou não dentro de cada grupo.

In [46]:
df.groupby(["type1", "legendary"])["attack"].describe()

                     count        mean        std    min     25%    50%  \
type1     legendary
Blastoise False        1.0   83.000000        NaN   83.0   83.00   83.0
Bug       False       82.0   69.719512  37.020940   10.0   45.00   64.0
          True         1.0  120.000000        NaN  120.0  120.00  120.0
Dark      False       43.0   80.534884  28.298030   28.0   60.00   85.0
          True         5.0  109.200000  20.388722   85.0   90.00  120.0
Dragon    False       26.0   98.769231  32.069060   50.0   75.00   92.5
          True        15.0  121.333333  29.968237   80.0  100.00  120.0
Electric  False       56.0   71.428571  23.486056   30.0   55.00   65.0
          True         7.0  103.142857  12.075161   85.0   95.00  105.0
Fairy     False       20.0   56.350000  22.193586   20.0   43.75   52.0
          True         3.0  143.666667  22.810816  130.0  130.50  131.0
Fighting  False       36.0   99.805556  27.429723   35.0   81.50  100.0
          True         9.0  124.444444  13.096861   90.0  125.00  130.0
Fire      False       62.0   84.693548  27.488053   30.0   64.25   84.0
          True         5.0  109.000000  15.165751   90.0  100.00  110.0
Flying    False        7.0   67.571429  21.983760   30.0   57.00   70.0
          True         2.0  107.500000  10.606602  100.0  103.75  107.5
Ghost     False       40.0   72.175000  27.725659   30.0   55.00   66.0
          True         3.0   95.000000  27.838822   65.0   82.50  100.0
Graass    False        1.0   50.000000        NaN   50.0   50.00   50.0
Grass     False       90.0   74.855556  29.225801   27.0   53.50   72.5
          True         4.0  105.750000  17.095321   90.0   97.50  101.5
Ground    False       38.0   88.052632  25.728255   40.0   70.50   83.5
          True         4.0  150.000000  22.730303  125.0  140.00  147.5
Ice       False       35.0   76.685714  31.057604   25.0   52.50   70.0
          True         3.0   93.333333  48.045118   50.0   67.50   85.0
Normal    False      113.0   73.495575  28.404956    5.0   55.00   75.0
          True         4.0  121.250000  34.189423   77.0  109.25  124.0
Poison    False       40.0   74.900000  19.215112   43.0   60.75   73.0
          True         2.0  100.000000  21.213203   85.0   92.50  100.0
Psychic   False       50.0   55.660000  27.174125   20.0   36.25   50.0
          True        30.0  111.066667  40.557268   29.0   85.00  106.0
Rock      False       56.0   89.875000  33.001963   40.0   60.00   86.5
          True         4.0  122.250000  28.640007  100.0  100.00  114.5
Steel     False       31.0   94.322581  29.943711   24.0   80.00   90.0
          True         8.0  103.875000  29.161802   65.0   86.25   97.5
Water     False      127.0   74.472441  29.070748   10.0   53.50   70.0
          True         9.0   93.777778  26.855064   72.0   75.00   80.0

                        75%    max
type1     legendary
Blastoise False       83.00   83.0
Bug       False       90.00  185.0
          True       120.00  120.0
Dark      False       93.50  150.0
          True       120.00  131.0
Dragon    False      120.00  170.0
          True       140.00  180.0
Electric  False       91.25  123.0
          True       113.50  115.0
Fairy     False       66.25  120.0
          True       150.50  170.0
Fighting  False      121.00  145.0
          True       130.00  130.0
Fire      False      103.00  160.0
          True       115.00  130.0
Flying    False       86.00   87.0
          True       111.25  115.0
Ghost     False       90.00  165.0
          True       110.00  120.0
Graass    False       50.00   50.0
Grass     False       97.25  181.0
          True       109.75  130.0
Ground    False      105.25  140.0
          True       157.50  180.0
Ice       False       92.50  160.0
          True       115.00  145.0
Normal    False       90.00  160.0
          True       136.00  160.0
Poison    False       90.50  106.0
          True       107.50  115.0
Psychic   False       65.00  165.0
          True       146.75  190.0
Rock      False      115.50  165.0
          True       136.75  160.0
Steel     False      110.00  150.0
          True       125.75  143.0
Water     False       91.00  155.0
          True       100.00  150.0

## Utilizando o .groupby() com o .describe()

Uma vez que nossos dados estejam agrupados por um determinado critérios, podemos utilizar o método .describe() do Pandas para visualizarmos algumas informações dos nossos registros agrupados.

No DataFrame abaixo estamos pedindo os detalhes dos dados de velocidade depois de ter agrupado nossos pokemons pelo tipo.

In [42]:
df.groupby("type1")["speed"].describe()

           count       mean        std   min    25%   50%     75%    max
type1
Blastoise    1.0  78.000000        NaN  78.0  78.00  78.0   78.00   78.0
Bug         83.0  63.421687  33.586481   5.0  38.00  60.0   85.00  160.0
Dark        48.0  76.937500  25.715635  20.0  60.00  71.5   98.25  125.0
Dragon      41.0  84.341463  24.146024  40.0  67.00  85.0  100.00  142.0
Electric    63.0  85.936508  31.961102  15.0  62.50  90.0  102.00  200.0
Fairy       23.0  59.739130  35.057378  15.0  34.50  52.0   73.50  148.0
Fighting    45.0  72.111111  28.724572  25.0  45.00  70.0   97.00  138.0
Fire        67.0  75.343284  25.450815  20.0  60.00  77.0   97.50  126.0
Flying       9.0  84.777778  26.952633  55.0  67.00  77.0  111.00  123.0
Ghost       43.0  64.139535  30.488547  15.0  39.00  56.0   87.50  130.0
Graass       1.0  60.000000        NaN  60.0  60.00  60.0   60.00   60.0
Grass       94.0  60.042553  27.930757  10.0  38.50  58.5   80.00  145.0
Ground      42.0  62.023810  27.473702  10.0  40.00  60.0   89.50  120.0
Ice         38.0  67.026316  29.057712  20.0  50.00  65.0   83.75  135.0
Normal     117.0  69.085470  27.837760   5.0  50.00  68.0   90.00  135.0
Poison      42.0  66.142857  28.809358  25.0  46.25  62.5   79.25  130.0
Psychic     80.0  79.675000  36.341828  15.0  48.75  80.0  100.00  180.0
Rock        60.0  57.166667  31.191680  10.0  33.75  50.0   70.00  150.0
Steel       39.0  53.333333  24.195838  23.0  33.50  50.0   67.50  110.0
Water      136.0  66.544118  25.119527   5.0  50.00  65.0   85.00  136.0